# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=64, unique=True)),
                ('sex', models.BooleanField(default=False)),
                ('icon', models.ImageField(upload_to='icon')),
                ('is_delete', models.BooleanField(default=False)),
                ('ticket', models.CharField(default=True, max_length=255)),
                ('out_time', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'axf_users',
            },
        ),
    ]
